dist: trusty
language: node_js
node_js:
- node

before_install:
- npm i -g npm@latest

addons:
  sonarcloud:
    organization: 'cartographers-2020'
    token: $SONAR_TOKEN

jobs:
  include:
    -stage: "Tests and Analysis"
    script:
      - npm run test
      - npm run cov-report
      - npm run lint -s
      - sonar-scanner -X -Dsonar.branch.name=$TRAVIS_BRANCH -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=JoshMcKinstry_WorldCraft

