dist: trusty
language: node_js
node_js:
- node

before_install:
- npm i -g npm@latest

jobs:
    include:
        - stage: "Tests and Analysis"
          script:
            - npm run test
            - npm run cov-report
            - npm run lint-detail -s
