dist: trusty
language: node_js
node_js:
- node

addons:
    sonarcloud:
        organization: "$SONAR_ORGANIZATION"
        token:
            secure: "$SONAR_TOKEN"
          
before_install:
- npm i -g npm@latest


script:
- sonar-scanner -Dsonar.verbose=true -X
